require("plugins")
require("keybinds")
require("options")
require("lsp")
require("telescope_config")
require("treesitter")
require("inlay_hints")

vim.cmd("colorscheme gruvbox")
vim.cmd("highlight Normal guibg=NONE")
vim.cmd("highlight LineNr guifg=#5eacd3")
