require("plugins")
require("keybinds")
require("options")
require("lsp")
require("telescope_config")
require("treesitter")

vim.cmd("colorscheme gruvbox")
vim.cmd("highlight Normal guibg=NONE")
vim.cmd("highlight LineNr guifg=#5eacd3")
vim.cmd("autocmd BufRead,BufNewFile   *.tex setlocal tabstop=2")
vim.cmd("autocmd BufRead,BufNewFile   *.tex setlocal shiftwidth=2")
